# fishros deploy tool 
# 所有的操作都在工程目录进行
# os / docker 
mode: os
env: nodejs
name: ros2cn
tag: main
stage:
  prepare:
    - npm run install-dep
  start:
    - npm run build
  end:
    - rm -rf /root/ros2/dev/ros2cn/*
    - cp -r docs/.vuepress/dist/* /root/ros2/dev/ros2cn/
    - rm -rf /root/ros2/master/ros2cn/*
    - cp -r docs/.vuepress/dist/* /root/ros2/master/ros2cn/
# 超时
timeout: 200
