# fishros deploy tool 所有的操作都在工程目录进行
name: ros2cn
tag: main
pipline:
  - install-dep
  - build
  - install
stages:
  install-dep:
    - npm run install-dep
  build:
    - npm run build
  install:
    - rm -rf /root/ros2/dev/ros2cn/*
    - cp -r docs/.vuepress/dist/* /root/ros2/dev/ros2cn/
    - rm -rf /root/ros2/master/ros2cn/*
    - cp -r docs/.vuepress/dist/* /root/ros2/master/ros2cn/
