# fishros deploy tool 
# 所有的操作都在工程目录进行
# os / docker 
mode: os
name: ros2cn
tag: main
stage:
  prepare:
    - npm run install-dep
  start:
    - npm run build
  end:
    - rm -rf /root/test/deploy/*
    - cp dist/* /root/test/deploy/
# 超时
timeout: 200